/*
 * This source file was generated by the Gradle 'init' task4
 */
package org.example;

import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static void fn2(int[] x) {
        x[0]=x[0]+1;
    }

    public static void main(String[] args) {

        simpleArray();

        /* 
        int y = 0;
        int z = 0;
        
        for(int x=100; x>=0; x--) {
            y+=x;
            System.out.println(x);


            
            if (x%2==0) {
                z+=x;
            }


            
        }

        int[] mBtArray = new int[10];
        Random rnd = new Random();
        rnd.nextInt(20);

        System.out.println(y);
        System.out.println(z);
        System.out.println(new App().getGreeting());
        System.out.println("DYLAN");

        int xexexe;
        for(xexexe=0; xexexe<=1000; xexexe++) {
            System.out.println(xexexe);
        }

        double el = 0.5;
        double sumthing = 0;
        for(int i = 0; i < 1000; i++) {
            sumthing += el;
            el= 0.5 * el;
        }

        System.out.println("🚟🚟🚟🚟🚟🚟🚟🫃🫃🫃🫃🫃🫃🫃🫃🫃🫃🚈🚈🚈🚈🚈🚈🚈🚈🚈🚈🚈🚈");
        System.out.println(sumthing);
        for(int i=0; i<10; i++) {
            mBtArray[i]=rnd.nextInt(20);
            System.out.println(mBtArray[i]);
        }   
        System.out.println("fihofwiogfne");

        int[]a = new int[1];
        a[0] = 7;
        fn2(a);
        System.out.println(a[0]);
        */
    }

    public static void simpleArray() {
        int [] parkst = new int[50];
        parkst[0] = 1;
        for (int govtctr = 1; govtctr<=49; govtctr++) {
            parkst[govtctr]= parkst[govtctr-1] * -5 + 4;
            System.out.println(parkst[govtctr]);
        }
    }
}
